name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 6) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 6) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_tcu
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_6
- st_zones_popden
- st_building_age

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: -0.42819462149111087
        st_building_age: -0.16309230062246408
        st_is_tcu: 0.20681674918000076
        st_zones_ln_empden_6: 0.14765256569792712
        st_zones_popden: -0.07118769100097487
    Std. Error:
        st_b_ln_non_residential_sqft: 0.006128677532905128
        st_building_age: 0.020651245646018855
        st_is_tcu: 0.0028593328600714845
        st_zones_ln_empden_6: 0.002396249583673842
        st_zones_popden: 0.02221979585098614
    T-Score:
        st_b_ln_non_residential_sqft: -69.86737663910623
        st_building_age: -7.897455844456772
        st_is_tcu: 72.33042087126235
        st_zones_ln_empden_6: 61.61819148719543
        st_zones_popden: -3.2037959069644413

probability_mode: single_chooser

log_likelihoods:
    convergence: -10632.005819239861
    'null': -17005.986908309435
    ratio: 0.37480806750210605
