name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 14) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 14) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_medical
- st_is_retail
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_14
- st_zones_popden
- st_zones_prop_industrial_buildings
- st_building_age

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: -0.7349252454850528
        st_building_age: -0.1154038761210464
        st_is_medical: 0.12695338492571948
        st_is_retail: -0.12495532889393847
        st_zones_ln_empden_14: 0.04374168642105125
        st_zones_popden: 0.06426521834145398
        st_zones_prop_industrial_buildings: -0.1211537901329685
    Std. Error:
        st_b_ln_non_residential_sqft: 0.005935251136272295
        st_building_age: 0.018969485561324825
        st_is_medical: 0.0017106732936657367
        st_is_retail: 0.008354612437383634
        st_zones_ln_empden_14: 0.0034844852619261113
        st_zones_popden: 0.015668829991995526
        st_zones_prop_industrial_buildings: 0.008830528448050524
    T-Score:
        st_b_ln_non_residential_sqft: -123.8237824501949
        st_building_age: -6.0836587132511895
        st_is_medical: 74.21252520618704
        st_is_retail: -14.956448288948998
        st_zones_ln_empden_14: 12.55327060757096
        st_zones_popden: 4.101468863615476
        st_zones_prop_industrial_buildings: -13.719879942147184

probability_mode: single_chooser

log_likelihoods:
    convergence: -12154.534338805332
    'null': -16985.579724019455
    ratio: 0.28442040034597704
