name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 14

choosers_predict_filters: household_type == 14

alts_fit_filters: (residential_units > 0)

alts_predict_filters: vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_sum_residential_units
- st_zones_prop_income_4
- st_zones_mean_age_of_head
- st_zones_mean_hh_size
- st_zones_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_residential_units: 0.3035312733998367
        st_b_ln_sqft_per_unit: 0.9135466904696719
        st_zones_mean_age_of_head: -0.11923509199916967
        st_zones_mean_hh_size: -0.3706837265034909
        st_zones_prop_income_4: 0.5211829762607146
        st_zones_prop_race_1: 0.2621884262255619
        st_zones_sum_residential_units: 0.044311328370126794
    Std. Error:
        st_b_ln_residential_units: 0.010629301863756286
        st_b_ln_sqft_per_unit: 0.07467317899871982
        st_zones_mean_age_of_head: 0.02909767639832583
        st_zones_mean_hh_size: 0.029367691235887002
        st_zones_prop_income_4: 0.030712397746441522
        st_zones_prop_race_1: 0.03745541306944034
        st_zones_sum_residential_units: 0.022519619995633337
    T-Score:
        st_b_ln_residential_units: 28.55608743550838
        st_b_ln_sqft_per_unit: 12.233933290630809
        st_zones_mean_age_of_head: -4.097753042783513
        st_zones_mean_hh_size: -12.622160983854236
        st_zones_prop_income_4: 16.969791175653203
        st_zones_prop_race_1: 7.000014276694225
        st_zones_sum_residential_units: 1.9676765584285603

probability_mode: single_chooser

log_likelihoods:
    convergence: -13098.504116514909
    'null': -13815.510557964428
    ratio: 0.05189865683510164
