name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 18

choosers_predict_filters: household_type == 18

alts_fit_filters: (residential_units > 0)

alts_predict_filters: vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_b_ln_residential_units
- st_b_ln_sqft_per_unit
- st_zones_sum_residential_units
- st_jobs_within_30_min
- st_zones_prop_income_4
- st_zones_mean_age_of_head
- st_zones_mean_hh_size
- st_zones_prop_race_1

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_residential_units: 0.3084786194709922
        st_b_ln_sqft_per_unit: 0.6358332911962524
        st_jobs_within_30_min: 0.1511286175056011
        st_zones_mean_age_of_head: -0.3681009255116653
        st_zones_mean_hh_size: -0.09725554803341813
        st_zones_prop_income_4: 0.44838364434042655
        st_zones_prop_race_1: 0.41919985829971185
        st_zones_sum_residential_units: 0.057356837991742814
    Std. Error:
        st_b_ln_residential_units: 0.010721756658024474
        st_b_ln_sqft_per_unit: 0.07909893459547425
        st_jobs_within_30_min: 0.028835842446727343
        st_zones_mean_age_of_head: 0.026730087834387458
        st_zones_mean_hh_size: 0.028428541128065192
        st_zones_prop_income_4: 0.030598577587231068
        st_zones_prop_race_1: 0.04235066836505525
        st_zones_sum_residential_units: 0.022755322075638847
    T-Score:
        st_b_ln_residential_units: 28.771275949460936
        st_b_ln_sqft_per_unit: 8.038455820524193
        st_jobs_within_30_min: 5.240998863993762
        st_zones_mean_age_of_head: -13.771033144085463
        st_zones_mean_hh_size: -3.421053074630186
        st_zones_prop_income_4: 14.653741438214409
        st_zones_prop_race_1: 9.898305610817836
        st_zones_sum_residential_units: 2.5205900316896543

probability_mode: single_chooser

log_likelihoods:
    convergence: -13144.279139849628
    'null': -13815.510557964428
    ratio: 0.04858535016122478
