name: RegressionModel

model_type: regression

fit_filters:
- building_type_id == 61
- non_residential_sqft > 0
- sqft_price_nonres > 1
- sqft_price_nonres < 650

predict_filters: building_type_id == 61

model_expression: np.log1p(sqft_price_nonres) ~ st_zones_logsum_job_low_income + st_zones_logsum_pop_low_income
    + st_zones_ln_empden_5 + st_b_ln_building_sqft + st_zones_prop_race_2 + st_b_total_jobs
    + st_zones_mean_non_residential_sqft + 1

ytransform: np.exp

fitted: true

fit_parameters:
    Coefficient:
        Intercept: 4.318220844549543
        st_b_ln_building_sqft: -0.21032564848681512
        st_b_total_jobs: 0.0303569328076385
        st_zones_ln_empden_5: 0.14575437352259404
        st_zones_logsum_job_low_income: -0.6788945740533718
        st_zones_logsum_pop_low_income: 0.5185501026413973
        st_zones_mean_non_residential_sqft: 0.02871870913989029
        st_zones_prop_race_2: -0.21670072880514518
    Std. Error:
        Intercept: 0.11112372524012572
        st_b_ln_building_sqft: 0.03144074210721608
        st_b_total_jobs: 0.015487896779129165
        st_zones_ln_empden_5: 0.030120554174201033
        st_zones_logsum_job_low_income: 0.4178542627785148
        st_zones_logsum_pop_low_income: 0.3931099414207298
        st_zones_mean_non_residential_sqft: 0.02009226110496563
        st_zones_prop_race_2: 0.09334683882440864
    T-Score:
        Intercept: 38.8595759836017
        st_b_ln_building_sqft: -6.689589188753358
        st_b_total_jobs: 1.9600422988708333
        st_zones_ln_empden_5: 4.839033594124112
        st_zones_logsum_job_low_income: -1.6247161618959538
        st_zones_logsum_pop_low_income: 1.3190968937781555
        st_zones_mean_non_residential_sqft: 1.4293418241908427
        st_zones_prop_race_2: -2.321457604073482

fit_rsquared_adj: 0.3014539491941355

fit_rsquared: 0.3245191489848952
