name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (building_id > 1) & household_type == 4

choosers_predict_filters: household_type == 4

alts_fit_filters: (residential_units > 0)

alts_predict_filters: vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 1000

estimation_sample_size: 2000

prediction_sample_size: null

model_expression:
- st_sqft_price_res
- st_b_ln_residential_units
- st_b_ln_building_sqft
- st_nodes_walk_percent_low_income
- st_drv_nearest_grocery

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_building_sqft: -0.04869557477834109
        st_b_ln_residential_units: 0.2655602690381562
        st_drv_nearest_grocery: -0.11300592709212585
        st_nodes_walk_percent_low_income: 0.7667826547061267
        st_sqft_price_res: -0.29153997611699617
    Std. Error:
        st_b_ln_building_sqft: 0.04118497934868848
        st_b_ln_residential_units: 0.022855346462183235
        st_drv_nearest_grocery: 0.03403635961177453
        st_nodes_walk_percent_low_income: 0.03208451583780699
        st_sqft_price_res: 0.04620316387490003
    T-Score:
        st_b_ln_building_sqft: -1.182362491093292
        st_b_ln_residential_units: 11.619174947864204
        st_drv_nearest_grocery: -3.3201531650591862
        st_nodes_walk_percent_low_income: 23.898838261495083
        st_sqft_price_res: -6.309956974080207

probability_mode: single_chooser

log_likelihoods:
    convergence: -12385.847385588468
    'null': -13815.510557964428
    ratio: 0.10348247112386166
