name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 4) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 4) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_industrial
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_4
- st_nodes_walk_log_sum_residential_units
- st_building_age
- st_nodes_drv_log_sum_45min_jobs

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.3593265753447175
        st_building_age: -0.2604228851045762
        st_is_industrial: 0.07380819219842834
        st_nodes_drv_log_sum_45min_jobs: 0.07911057270290243
        st_nodes_walk_log_sum_residential_units: -0.08923890035913151
        st_zones_ln_empden_4: 0.2308246863079484
    Std. Error:
        st_b_ln_non_residential_sqft: 0.007297128488937656
        st_building_age: 0.019814704955129603
        st_is_industrial: 0.002909244477485854
        st_nodes_drv_log_sum_45min_jobs: 0.02509154598142429
        st_nodes_walk_log_sum_residential_units: 0.011568799892366713
        st_zones_ln_empden_4: 0.0055262011187961575
    T-Score:
        st_b_ln_non_residential_sqft: 186.28239552112004
        st_building_age: -13.142910060700059
        st_is_industrial: 25.370226795863093
        st_nodes_drv_log_sum_45min_jobs: 3.1528775772313664
        st_nodes_walk_log_sum_residential_units: -7.71375606712783
        st_zones_ln_empden_4: 41.76914327689758

probability_mode: single_chooser

log_likelihoods:
    convergence: -11114.212074204615
    'null': -17002.58571092777
    ratio: 0.34632224397131695
