name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 14) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 14) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_medical
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_14
- st_nodes_walk_medical
- st_nodes_drv_log_sum_60min_jobs
- st_zones_population

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.2744435182669576
        st_is_medical: 0.15733842938263418
        st_nodes_drv_log_sum_60min_jobs: 0.05674433346761471
        st_nodes_walk_medical: 0.24243393925012674
        st_zones_ln_empden_14: 0.16227459006046205
        st_zones_population: 0.16595629396813538
    Std. Error:
        st_b_ln_non_residential_sqft: 0.006426548347706431
        st_is_medical: 0.001820300416521339
        st_nodes_drv_log_sum_60min_jobs: 0.021402582788382505
        st_nodes_walk_medical: 0.013740143845933497
        st_zones_ln_empden_14: 0.0049732145956826335
        st_zones_population: 0.01911275420287581
    T-Score:
        st_b_ln_non_residential_sqft: 198.30917769751056
        st_is_medical: 86.43541909599388
        st_nodes_drv_log_sum_60min_jobs: 2.651284381360552
        st_nodes_walk_medical: 17.64420678331377
        st_zones_ln_empden_14: 32.62971805023988
        st_zones_population: 8.68301303969915

probability_mode: single_chooser

log_likelihoods:
    convergence: -9281.9949137138
    'null': -16988.98092140112
    ratio: 0.45364616296547744
