name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 16) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 16) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_retail
- st_building_type_id_is_26
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_16
- st_nodes_drv_log_sum_30min_jobs
- st_building_age

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.4954047758602096
        st_building_age: -0.3426325934860601
        st_building_type_id_is_26: 0.1501678973833919
        st_is_retail: 0.311623138067122
        st_nodes_drv_log_sum_30min_jobs: -0.00022647233497654682
        st_zones_ln_empden_16: 0.15908156656716377
    Std. Error:
        st_b_ln_non_residential_sqft: 0.008905059992380698
        st_building_age: 0.016963680203950726
        st_building_type_id_is_26: 0.002245445146401453
        st_is_retail: 0.006985607914718749
        st_nodes_drv_log_sum_30min_jobs: 0.019309859840466962
        st_zones_ln_empden_16: 0.004831974705869424
    T-Score:
        st_b_ln_non_residential_sqft: 167.92753525969508
        st_building_age: -20.198010653741473
        st_building_type_id_is_26: 66.87667148050832
        st_is_retail: 44.60930843406324
        st_nodes_drv_log_sum_30min_jobs: -0.011728326194369214
        st_zones_ln_empden_16: 32.922681978017515

probability_mode: single_chooser

log_likelihoods:
    convergence: -9809.093434813896
    'null': -17005.986908309435
    ratio: 0.423197636943905
