name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 3) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 3) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_industrial
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_3
- st_nodes_walk_log_sum_residential_units
- st_building_age
- st_is_office

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.859266639837162
        st_building_age: -0.14302612099565318
        st_is_industrial: 0.21271647268556734
        st_is_office: 0.11708849814123004
        st_nodes_walk_log_sum_residential_units: -0.040487108807452474
        st_zones_ln_empden_3: 0.1644703713108509
    Std. Error:
        st_b_ln_non_residential_sqft: 0.010831743866370879
        st_building_age: 0.024595319122054208
        st_is_industrial: 0.0044177019851150716
        st_is_office: 0.006935271847955732
        st_nodes_walk_log_sum_residential_units: 0.013948026034921093
        st_zones_ln_empden_3: 0.007247035662650534
    T-Score:
        st_b_ln_non_residential_sqft: 171.64979737100262
        st_building_age: -5.815176468574626
        st_is_industrial: 48.150933087449204
        st_is_office: 16.88304376644493
        st_nodes_walk_log_sum_residential_units: -2.9027124487785283
        st_zones_ln_empden_3: 22.694847792524513

probability_mode: single_chooser

log_likelihoods:
    convergence: -7077.827058245155
    'null': -17005.986908309435
    ratio: 0.5838038041304854
