name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 10) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 10) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_office
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_10
- st_nodes_drv_log_sum_45min_jobs
- st_building_age
- st_nodes_walk_residential

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.7217117658175778
        st_building_age: -0.30549937201495675
        st_is_office: 0.18397208547269442
        st_nodes_drv_log_sum_45min_jobs: 0.03348253902461646
        st_nodes_walk_residential: 0.03272255181275839
        st_zones_ln_empden_10: 0.1894854513370933
    Std. Error:
        st_b_ln_non_residential_sqft: 0.007175322586455195
        st_building_age: 0.020819652502916303
        st_is_office: 0.003954515716293268
        st_nodes_drv_log_sum_45min_jobs: 0.02946112347707632
        st_nodes_walk_residential: 0.015876095227939625
        st_zones_ln_empden_10: 0.004138249552975007
    T-Score:
        st_b_ln_non_residential_sqft: 239.94903993133923
        st_building_age: -14.673605718066815
        st_is_office: 46.52202663266669
        st_nodes_drv_log_sum_45min_jobs: 1.1364990561432322
        st_nodes_walk_residential: 2.0611209080663264
        st_zones_ln_empden_10: 45.78879280029676

probability_mode: single_chooser

log_likelihoods:
    convergence: -7628.500143737998
    'null': -16995.783316164445
    ratio: 0.5511533654066629
