elcm:
  - elcm_regional_largearea_control/elcm200003.yaml
  - elcm_regional_largearea_control/elcm200005.yaml
  - elcm_regional_largearea_control/elcm200093.yaml
  - elcm_regional_largearea_control/elcm200099.yaml
  - elcm_regional_largearea_control/elcm200115.yaml
  - elcm_regional_largearea_control/elcm200125.yaml
  - elcm_regional_largearea_control/elcm200147.yaml
  - elcm_regional_largearea_control/elcm200161.yaml
  - elcm_regional_largearea_control/elcm300003.yaml
  - elcm_regional_largearea_control/elcm300005.yaml
  - elcm_regional_largearea_control/elcm300093.yaml
  - elcm_regional_largearea_control/elcm300099.yaml
  - elcm_regional_largearea_control/elcm300115.yaml
  - elcm_regional_largearea_control/elcm300125.yaml
  - elcm_regional_largearea_control/elcm300147.yaml
  - elcm_regional_largearea_control/elcm300161.yaml
  - elcm_regional_largearea_control/elcm400003.yaml
  - elcm_regional_largearea_control/elcm400005.yaml
  - elcm_regional_largearea_control/elcm400093.yaml
  - elcm_regional_largearea_control/elcm400099.yaml
  - elcm_regional_largearea_control/elcm400115.yaml
  - elcm_regional_largearea_control/elcm400125.yaml
  - elcm_regional_largearea_control/elcm400147.yaml
  - elcm_regional_largearea_control/elcm400161.yaml
  - elcm_regional_largearea_control/elcm500003.yaml
  - elcm_regional_largearea_control/elcm500005.yaml
  - elcm_regional_largearea_control/elcm500093.yaml
  - elcm_regional_largearea_control/elcm500099.yaml
  - elcm_regional_largearea_control/elcm500115.yaml
  - elcm_regional_largearea_control/elcm500125.yaml
  - elcm_regional_largearea_control/elcm500147.yaml
  - elcm_regional_largearea_control/elcm500161.yaml
  - elcm_regional_largearea_control/elcm600003.yaml
  - elcm_regional_largearea_control/elcm600005.yaml
  - elcm_regional_largearea_control/elcm600093.yaml
  - elcm_regional_largearea_control/elcm600099.yaml
  - elcm_regional_largearea_control/elcm600115.yaml
  - elcm_regional_largearea_control/elcm600125.yaml
  - elcm_regional_largearea_control/elcm600147.yaml
  - elcm_regional_largearea_control/elcm600161.yaml
  - elcm_regional_largearea_control/elcm800003.yaml
  - elcm_regional_largearea_control/elcm800005.yaml
  - elcm_regional_largearea_control/elcm800093.yaml
  - elcm_regional_largearea_control/elcm800099.yaml
  - elcm_regional_largearea_control/elcm800115.yaml
  - elcm_regional_largearea_control/elcm800125.yaml
  - elcm_regional_largearea_control/elcm800147.yaml
  - elcm_regional_largearea_control/elcm800161.yaml
  - elcm_regional_largearea_control/elcm900003.yaml
  - elcm_regional_largearea_control/elcm900005.yaml
  - elcm_regional_largearea_control/elcm900093.yaml
  - elcm_regional_largearea_control/elcm900099.yaml
  - elcm_regional_largearea_control/elcm900115.yaml
  - elcm_regional_largearea_control/elcm900125.yaml
  - elcm_regional_largearea_control/elcm900147.yaml
  - elcm_regional_largearea_control/elcm900161.yaml
  - elcm_regional_largearea_control/elcm1000003.yaml
  - elcm_regional_largearea_control/elcm1000005.yaml
  - elcm_regional_largearea_control/elcm1000093.yaml
  - elcm_regional_largearea_control/elcm1000099.yaml
  - elcm_regional_largearea_control/elcm1000115.yaml
  - elcm_regional_largearea_control/elcm1000125.yaml
  - elcm_regional_largearea_control/elcm1000147.yaml
  - elcm_regional_largearea_control/elcm1000161.yaml
  - elcm_regional_largearea_control/elcm1100003.yaml
  - elcm_regional_largearea_control/elcm1100005.yaml
  - elcm_regional_largearea_control/elcm1100093.yaml
  - elcm_regional_largearea_control/elcm1100099.yaml
  - elcm_regional_largearea_control/elcm1100115.yaml
  - elcm_regional_largearea_control/elcm1100125.yaml
  - elcm_regional_largearea_control/elcm1100147.yaml
  - elcm_regional_largearea_control/elcm1100161.yaml
  - elcm_regional_largearea_control/elcm1400003.yaml
  - elcm_regional_largearea_control/elcm1400005.yaml
  - elcm_regional_largearea_control/elcm1400093.yaml
  - elcm_regional_largearea_control/elcm1400099.yaml
  - elcm_regional_largearea_control/elcm1400115.yaml
  - elcm_regional_largearea_control/elcm1400125.yaml
  - elcm_regional_largearea_control/elcm1400147.yaml
  - elcm_regional_largearea_control/elcm1400161.yaml
  - elcm_regional_largearea_control/elcm1600003.yaml
  - elcm_regional_largearea_control/elcm1600005.yaml
  - elcm_regional_largearea_control/elcm1600093.yaml
  - elcm_regional_largearea_control/elcm1600099.yaml
  - elcm_regional_largearea_control/elcm1600115.yaml
  - elcm_regional_largearea_control/elcm1600125.yaml
  - elcm_regional_largearea_control/elcm1600147.yaml
  - elcm_regional_largearea_control/elcm1600161.yaml
  - elcm_regional_largearea_control/elcm1700003.yaml
  - elcm_regional_largearea_control/elcm1700005.yaml
  - elcm_regional_largearea_control/elcm1700093.yaml
  - elcm_regional_largearea_control/elcm1700099.yaml
  - elcm_regional_largearea_control/elcm1700115.yaml
  - elcm_regional_largearea_control/elcm1700125.yaml
  - elcm_regional_largearea_control/elcm1700147.yaml
  - elcm_regional_largearea_control/elcm1700161.yaml

hlcm:
  - hlcm_regional_largearea_control/hlcm100003.yaml
  - hlcm_regional_largearea_control/hlcm100005.yaml
  - hlcm_regional_largearea_control/hlcm10003.yaml
  - hlcm_regional_largearea_control/hlcm10005.yaml
  - hlcm_regional_largearea_control/hlcm100093.yaml
  - hlcm_regional_largearea_control/hlcm100099.yaml
  - hlcm_regional_largearea_control/hlcm100115.yaml
  - hlcm_regional_largearea_control/hlcm100125.yaml
  - hlcm_regional_largearea_control/hlcm100147.yaml
  - hlcm_regional_largearea_control/hlcm100161.yaml
  - hlcm_regional_largearea_control/hlcm10093.yaml
  - hlcm_regional_largearea_control/hlcm10099.yaml
  - hlcm_regional_largearea_control/hlcm10115.yaml
  - hlcm_regional_largearea_control/hlcm10125.yaml
  - hlcm_regional_largearea_control/hlcm10147.yaml
  - hlcm_regional_largearea_control/hlcm10161.yaml
  - hlcm_regional_largearea_control/hlcm110003.yaml
  - hlcm_regional_largearea_control/hlcm110005.yaml
  - hlcm_regional_largearea_control/hlcm110093.yaml
  - hlcm_regional_largearea_control/hlcm110099.yaml
  - hlcm_regional_largearea_control/hlcm110115.yaml
  - hlcm_regional_largearea_control/hlcm110125.yaml
  - hlcm_regional_largearea_control/hlcm110147.yaml
  - hlcm_regional_largearea_control/hlcm110161.yaml
  - hlcm_regional_largearea_control/hlcm120003.yaml
  - hlcm_regional_largearea_control/hlcm120005.yaml
  - hlcm_regional_largearea_control/hlcm120093.yaml
  - hlcm_regional_largearea_control/hlcm120099.yaml
  - hlcm_regional_largearea_control/hlcm120115.yaml
  - hlcm_regional_largearea_control/hlcm120125.yaml
  - hlcm_regional_largearea_control/hlcm120147.yaml
  - hlcm_regional_largearea_control/hlcm120161.yaml
  - hlcm_regional_largearea_control/hlcm130003.yaml
  - hlcm_regional_largearea_control/hlcm130005.yaml
  - hlcm_regional_largearea_control/hlcm130093.yaml
  - hlcm_regional_largearea_control/hlcm130099.yaml
  - hlcm_regional_largearea_control/hlcm130115.yaml
  - hlcm_regional_largearea_control/hlcm130125.yaml
  - hlcm_regional_largearea_control/hlcm130147.yaml
  - hlcm_regional_largearea_control/hlcm130161.yaml
  - hlcm_regional_largearea_control/hlcm140003.yaml
  - hlcm_regional_largearea_control/hlcm140005.yaml
  - hlcm_regional_largearea_control/hlcm140093.yaml
  - hlcm_regional_largearea_control/hlcm140099.yaml
  - hlcm_regional_largearea_control/hlcm140115.yaml
  - hlcm_regional_largearea_control/hlcm140125.yaml
  - hlcm_regional_largearea_control/hlcm140147.yaml
  - hlcm_regional_largearea_control/hlcm140161.yaml
  - hlcm_regional_largearea_control/hlcm150003.yaml
  - hlcm_regional_largearea_control/hlcm150005.yaml
  - hlcm_regional_largearea_control/hlcm150093.yaml
  - hlcm_regional_largearea_control/hlcm150099.yaml
  - hlcm_regional_largearea_control/hlcm150115.yaml
  - hlcm_regional_largearea_control/hlcm150125.yaml
  - hlcm_regional_largearea_control/hlcm150147.yaml
  - hlcm_regional_largearea_control/hlcm150161.yaml
  - hlcm_regional_largearea_control/hlcm160003.yaml
  - hlcm_regional_largearea_control/hlcm160005.yaml
  - hlcm_regional_largearea_control/hlcm160093.yaml
  - hlcm_regional_largearea_control/hlcm160099.yaml
  - hlcm_regional_largearea_control/hlcm160115.yaml
  - hlcm_regional_largearea_control/hlcm160125.yaml
  - hlcm_regional_largearea_control/hlcm160147.yaml
  - hlcm_regional_largearea_control/hlcm160161.yaml
  - hlcm_regional_largearea_control/hlcm170003.yaml
  - hlcm_regional_largearea_control/hlcm170005.yaml
  - hlcm_regional_largearea_control/hlcm170093.yaml
  - hlcm_regional_largearea_control/hlcm170099.yaml
  - hlcm_regional_largearea_control/hlcm170115.yaml
  - hlcm_regional_largearea_control/hlcm170125.yaml
  - hlcm_regional_largearea_control/hlcm170147.yaml
  - hlcm_regional_largearea_control/hlcm170161.yaml
  - hlcm_regional_largearea_control/hlcm180003.yaml
  - hlcm_regional_largearea_control/hlcm180005.yaml
  - hlcm_regional_largearea_control/hlcm180093.yaml
  - hlcm_regional_largearea_control/hlcm180099.yaml
  - hlcm_regional_largearea_control/hlcm180115.yaml
  - hlcm_regional_largearea_control/hlcm180125.yaml
  - hlcm_regional_largearea_control/hlcm180147.yaml
  - hlcm_regional_largearea_control/hlcm180161.yaml
  - hlcm_regional_largearea_control/hlcm20003.yaml
  - hlcm_regional_largearea_control/hlcm20005.yaml
  - hlcm_regional_largearea_control/hlcm20093.yaml
  - hlcm_regional_largearea_control/hlcm20099.yaml
  - hlcm_regional_largearea_control/hlcm20115.yaml
  - hlcm_regional_largearea_control/hlcm20125.yaml
  - hlcm_regional_largearea_control/hlcm20147.yaml
  - hlcm_regional_largearea_control/hlcm20161.yaml
  - hlcm_regional_largearea_control/hlcm30003.yaml
  - hlcm_regional_largearea_control/hlcm30005.yaml
  - hlcm_regional_largearea_control/hlcm30093.yaml
  - hlcm_regional_largearea_control/hlcm30099.yaml
  - hlcm_regional_largearea_control/hlcm30115.yaml
  - hlcm_regional_largearea_control/hlcm30125.yaml
  - hlcm_regional_largearea_control/hlcm30147.yaml
  - hlcm_regional_largearea_control/hlcm30161.yaml
  - hlcm_regional_largearea_control/hlcm40003.yaml
  - hlcm_regional_largearea_control/hlcm40005.yaml
  - hlcm_regional_largearea_control/hlcm40093.yaml
  - hlcm_regional_largearea_control/hlcm40099.yaml
  - hlcm_regional_largearea_control/hlcm40115.yaml
  - hlcm_regional_largearea_control/hlcm40125.yaml
  - hlcm_regional_largearea_control/hlcm40147.yaml
  - hlcm_regional_largearea_control/hlcm40161.yaml
  - hlcm_regional_largearea_control/hlcm50003.yaml
  - hlcm_regional_largearea_control/hlcm50005.yaml
  - hlcm_regional_largearea_control/hlcm50093.yaml
  - hlcm_regional_largearea_control/hlcm50099.yaml
  - hlcm_regional_largearea_control/hlcm50115.yaml
  - hlcm_regional_largearea_control/hlcm50125.yaml
  - hlcm_regional_largearea_control/hlcm50147.yaml
  - hlcm_regional_largearea_control/hlcm50161.yaml
  - hlcm_regional_largearea_control/hlcm60003.yaml
  - hlcm_regional_largearea_control/hlcm60005.yaml
  - hlcm_regional_largearea_control/hlcm60093.yaml
  - hlcm_regional_largearea_control/hlcm60099.yaml
  - hlcm_regional_largearea_control/hlcm60115.yaml
  - hlcm_regional_largearea_control/hlcm60125.yaml
  - hlcm_regional_largearea_control/hlcm60147.yaml
  - hlcm_regional_largearea_control/hlcm60161.yaml
  - hlcm_regional_largearea_control/hlcm70003.yaml
  - hlcm_regional_largearea_control/hlcm70005.yaml
  - hlcm_regional_largearea_control/hlcm70093.yaml
  - hlcm_regional_largearea_control/hlcm70099.yaml
  - hlcm_regional_largearea_control/hlcm70115.yaml
  - hlcm_regional_largearea_control/hlcm70125.yaml
  - hlcm_regional_largearea_control/hlcm70147.yaml
  - hlcm_regional_largearea_control/hlcm70161.yaml
  - hlcm_regional_largearea_control/hlcm80003.yaml
  - hlcm_regional_largearea_control/hlcm80005.yaml
  - hlcm_regional_largearea_control/hlcm80093.yaml
  - hlcm_regional_largearea_control/hlcm80099.yaml
  - hlcm_regional_largearea_control/hlcm80115.yaml
  - hlcm_regional_largearea_control/hlcm80125.yaml
  - hlcm_regional_largearea_control/hlcm80147.yaml
  - hlcm_regional_largearea_control/hlcm80161.yaml
  - hlcm_regional_largearea_control/hlcm90003.yaml
  - hlcm_regional_largearea_control/hlcm90005.yaml
  - hlcm_regional_largearea_control/hlcm90093.yaml
  - hlcm_regional_largearea_control/hlcm90099.yaml
  - hlcm_regional_largearea_control/hlcm90115.yaml
  - hlcm_regional_largearea_control/hlcm90125.yaml
  - hlcm_regional_largearea_control/hlcm90147.yaml
  - hlcm_regional_largearea_control/hlcm90161.yaml

#res_repm:
#  - repm_regional/res_repm81.yaml
#  - repm_regional/res_repm82.yaml
#  - repm_regional/res_repm83.yaml
#  - repm_regional/res_repm84.yaml
#nonres_repm:
#  - repm_regional/nonres_repm21.yaml
#  - repm_regional/nonres_repm22.yaml
#  - repm_regional/nonres_repm23.yaml
#  - repm_regional/nonres_repm24.yaml
#  - repm_regional/nonres_repm31.yaml
#  - repm_regional/nonres_repm32.yaml
#  - repm_regional/nonres_repm33.yaml
#  - repm_regional/nonres_repm41.yaml
#  - repm_regional/nonres_repm42.yaml
#  - repm_regional/nonres_repm43.yaml
#  - repm_regional/nonres_repm51.yaml
#  - repm_regional/nonres_repm52.yaml
#  - repm_regional/nonres_repm53.yaml
#  - repm_regional/nonres_repm61.yaml
#  - repm_regional/nonres_repm62.yaml
#  - repm_regional/nonres_repm71.yaml