name: RegressionModel

model_type: regression

fit_filters:
- building_type_id == 42
- non_residential_sqft > 0
- sqft_price_nonres > 1
- sqft_price_nonres < 650

predict_filters: building_type_id == 42

model_expression: np.log1p(sqft_price_nonres) ~ st_zones_logsum_job_low_income + st_zones_prop_income_4
    + st_bldg_empratio_18 + st_zones_ln_empden + st_b_ln_building_sqft + 1

ytransform: np.exp

fitted: true

fit_parameters:
    Coefficient:
        Intercept: 4.709880075057468
        st_b_ln_building_sqft: -0.25757983236088816
        st_bldg_empratio_18: -0.030784475356589652
        st_zones_ln_empden: 0.2331574659708311
        st_zones_logsum_job_low_income: -0.17518580814938392
        st_zones_prop_income_4: 0.2771995171388587
    Std. Error:
        Intercept: 0.12989268789935637
        st_b_ln_building_sqft: 0.042730459056687355
        st_bldg_empratio_18: 0.02055234647574855
        st_zones_ln_empden: 0.08566801686545072
        st_zones_logsum_job_low_income: 0.10907408732744069
        st_zones_prop_income_4: 0.11122857279186302
    T-Score:
        Intercept: 36.25977836956291
        st_b_ln_building_sqft: -6.028014630481174
        st_bldg_empratio_18: -1.4978569669850037
        st_zones_ln_empden: 2.721639586183321
        st_zones_logsum_job_low_income: -1.606117570559868
        st_zones_prop_income_4: 2.492161053415381

fit_rsquared_adj: 0.45633508204668816

fit_rsquared: 0.4925794099102423
