name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 8) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 8) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_office
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_8
- st_jobs_within_30_min
- st_zones_popden
- st_building_age

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.531058759161102
        st_building_age: -0.20544265751877244
        st_is_office: 0.16407493366418005
        st_jobs_within_30_min: 0.03765728039802008
        st_zones_ln_empden_8: 0.12377429748177846
        st_zones_popden: -0.07953167848763822
    Std. Error:
        st_b_ln_non_residential_sqft: 0.005866795570150646
        st_building_age: 0.01790741670715858
        st_is_office: 0.0038627785565425194
        st_jobs_within_30_min: 0.019838725325389585
        st_zones_ln_empden_8: 0.0025728022330150815
        st_zones_popden: 0.013285211153434747
    T-Score:
        st_b_ln_non_residential_sqft: 260.97019077175514
        st_building_age: -11.472489911771902
        st_is_office: 42.475883942733596
        st_jobs_within_30_min: 1.8981703602613178
        st_zones_ln_empden_8: 48.10874924370952
        st_zones_popden: -5.986482079140772

probability_mode: single_chooser

log_likelihoods:
    convergence: -9078.547579723338
    'null': -16961.771342347813
    ratio: 0.464764180787105
