name: MNLDiscreteChoiceModel

model_type: discretechoice

choosers_fit_filters: (sector_id == 6) & (home_based_status == 0)

choosers_predict_filters: (sector_id == 6) & (home_based_status == 0)

alts_fit_filters: non_residential_sqft > 0

alts_predict_filters: non_residential_sqft > 0

interaction_predict_filters: null

choice_column: building_id

sample_size: 30

estimation_sample_size: 5000

prediction_sample_size: null

model_expression:
- st_is_tcu
- st_b_ln_non_residential_sqft
- st_zones_ln_empden_6
- st_zones_popden
- st_building_age

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        st_b_ln_non_residential_sqft: 1.3963782913865737
        st_building_age: -0.1841133452297741
        st_is_tcu: 0.14287275568386867
        st_zones_ln_empden_6: 0.21188281234670345
        st_zones_popden: -0.1111332340080679
    Std. Error:
        st_b_ln_non_residential_sqft: 0.006745844947841623
        st_building_age: 0.024837034710577462
        st_is_tcu: 0.0032270617827388996
        st_zones_ln_empden_6: 0.003737691958830635
        st_zones_popden: 0.023516258577001424
    T-Score:
        st_b_ln_non_residential_sqft: 206.99827852304165
        st_building_age: -7.412855333787689
        st_is_tcu: 44.27332518022276
        st_zones_ln_empden_6: 56.6881419551205
        st_zones_popden: -4.725804219415867

probability_mode: single_chooser

log_likelihoods:
    convergence: -7847.918901682957
    'null': -17005.986908309435
    ratio: 0.538520231492809
